### ISSUE TITLE
MacのChromeで等幅が効かない

### ISSUE THREAD

**Issue by tokiwoousaka** [tokiwoousaka/takahashi#5]
Twitterに報告あったのでissue立てました。

https://twitter.com/amutake_s/status/566575390081040385

**Comment by notogawa** [comment]
fontFamilyのリストがSansSerif, Monospaceになってるからでは

**Comment by tokiwoousaka** [comment]
ありがとうございます。CSSは詳しくないのですが、どのように対処すればブラウザ依存の少ない等幅設定が出来るか教えていただけますか？

**Comment by amutake** [comment]
Chrome の "設定" → "フォントをカスタマイズ" のところで serif, sans-serif, monospace などが指定されていたときのデフォルトのフォントを決めることができるのですが、そこが Osaka になっていました。(ここを等幅フォントにすると直りました)
これが Chrome デフォルトのものなのか、それとも自分が以前変えていて忘れてしまったのかはわからないです。
いずれにしても、monospace ではなく特定の等幅フォントを指定すれば直ると思います。

**Comment by notogawa** [comment]
まず，現状sans-serifをsens-serifとtypoしてます．FontFamily型のコンストラクタも同様です．
多くの環境ではsens-serifという名を持つ特定フォントは無いでしょうから，総称フォントファミリmonospaceが選択され，ブラウザ(orシステム)デフォルトの等幅フォントが使われる状態になっています．

通常は，特定フォントで各システムに入っていそうな等幅フォントを並べ，最後に総称フォントファミリmonospaceにfallbackするよう指定するのがよいと思います．

```
[ FontName "OSXに入ってそうな等幅フォント名"
, FontName "Windowsに入ってそうな等幅フォント名"
, ...
, Monospace
]
```

ちなみに，今現在githubのコードブロックに入ってるfont-family指定は

```
Consolas, "Liberation Mono", Menlo, Courier, monospace;
```

のようです．

**Comment by tokiwoousaka** [comment]
なるほど、ありがとうございます。たいぽは恥ずかしいですね・・・///
近日中にGithubと同様の設定になるように対応しようと思います。

**Comment by tokiwoousaka** [comment]
Githubと同様の設定になるよう修正入れました。

https://github.com/tokiwoousaka/takahashi/commit/90ec32e84f0ec99134f114513f18ac17e0bf45ed

これで修正出来ている事が確認できればCloseします。

**Comment by tokiwoousaka** [comment]
なんかその後指摘無いですし、音沙汰無いので閉じちゃいますね……もし直ってなくて、誰か気づいたらまた上げるでしょう。。。
